var autocompleteArr = [
  // A
  "A-Plus",
  "A.C. Moore",
  "A.T. Williams Oil Co.",
  "ABC Stores",
  "ABC Warehouse",
  "ACME Comics & Collectibles",
  "Aaron's, Inc.",
  "Abercrombie & Fitch",
  "Abraham & Straus",
  "Abt Electronics",
  "Acme Markets",
  "Acorn Stores",
  "Adorama",
  "Against All Odds",
  "Al's Formal Wear",
  "Alarm.com",
  "Alaska Commercial Company",
  "Albertsons",
  "Alfred Angelo",
  "Alife Rivington Club",
  "Alkemeyer Commercial Buildings",
  "All Pro Sound",
  "Allied Stores",
  "Allsup's",
  "American Apparel",
  "American Eagle Outfitters",
  "Ampm",
  "Anchor Blue Clothing Company",
  "Anderson-Little",
  "Andrew Saks",
  "Andy & Evan",
  "Anine Bing",
  "Ann Inc.",
  "Anna Sui",
  "Anna's Linens",
  "Anthropologie",
  "Apogee Components",
  "Apple Inc.",
  "Apple Store",
  "Arhaus",
  "Army and Air Force Exchange Service",
  "Ascena Retail Group",
  "At Home",
  "Audio Advice, Inc.",
  "AutoNation",
  "Avenue",
  "Avon Products",
  "Aéropostale",
  // B
  "B&H Photo Video",
  "BCBG Max Azria",
  "BHLDN",
  "BJ's Wholesale Club",
  "Ballard Designs",
  "Banana Republic",
  "Barneys New York",
  "Barneys Warehouse",
  "Bath & Body Works",
  "Battery Giant",
  "Bealls",
  "Bebe Stores",
  "Bed Bath & Beyond",
  "Belk",
  "Ben Cooper, Inc.",
  "Ben's Garden",
  "Benjamin Moore & Co.",
  "Bergdorf Goodman",
  "Bergner's",
  "Berkshire Hathaway",
  "Best & Co.",
  "Best Buy",
  "BevMo!",
  "Big Lots",
  "Bigsby & Kruthers",
  "Bijoux Terner",
  "BikiniLuxe",
  "Billionaire Boys Club",
  "Black Star Co-op",
  "Blair Corporation",
  "Blick Art Materials",
  "Bloomingdale's",
  "Blue Tree",
  "Boeing Store",
  "Bon Worth",
  "Bonobos",
  "Boscov's",
  "Boston Store",
  "Bowlin Travel Centers",
  "Brayola",
  "Break Time",
  "Brideside",
  "Brighton Collectibles",
  "Brook Mays",
  "Brooks Brothers",
  "Buc-ee's",
  "Buckle",
  "Buffalo Exchange",
  "Build-A-Bear Workshop",
  "Buy Buy Baby",
  "Buyer's Best Friend",
  // C
  "C. Crane Company",
  "C. Crawford Hollidge",
  "C. Wonder",
  "CHS Inc.",
  "CJ Banks",
  "CST Brands",
  "CVS Pharmacy",
  "Calumet Photographic",
  "Camera World",
  "Camp Beverly Hills",
  "Campmor",
  "CarMax",
  "Carson's",
  "Cascio Interstate Music",
  "Casey's General Stores",
  "Cash America International",
  "Cato Corporation",
  "Cavender's",
  "Century 21",
  "Charles S. Richardson",
  "Charlotte Russe",
  "Charming Charlie",
  "Charming Shoppes",
  "Chess King",
  "Chico's",
  "Christopher & Banks",
  "Circle K",
  "Circuit City Corporation",
  "Citi Trends",
  "Citizen's co-op",
  "City Gear",
  "Claire's",
  "Cloud 9 Living",
  "Club Monaco",
  "Coldwater Creek",
  "Colorado Trading & Clothing",
  "Comics and Comix",
  "CompUSA",
  "Computer City",
  "Conn's",
  "Consumers' Cooperative of Berkeley",
  "Convenient Food Mart",
  "Costco",
  "Country Junction",
  "County Seat",
  "Coup d'etat Brooklyn",
  "Cracker Barrel",
  "Crate & Barrel",
  "Crazy Eddie",
  "Crazy Shirts",
  "Crutchfield Corporation",
  "Crystal Rock Holdings",
  "Cumberland Farms",
  "Curacao",
  "Curtis Mathes Corporation",
  // D
  "DKNY",
  "DL1961",
  "Dairy Barn",
  "Daniel Smith",
  "Daqo New Energy",
  "Dari Mart",
  "Dash",
  "Dash's Designer",
  "Davenport Cash Store",
  "David's Bridal",
  "Davidson's",
  "De Pinna",
  "Deb Shops",
  "Delia's",
  "Delphi Glass",
  "Denim & Soul",
  "Deseret Industries",
  "Designer Bride",
  "Destination Maternity",
  "Destination XL Group",
  "Dick's Sporting Goods",
  "Digital Ocean",
  "Dillard's",
  "Disney Store",
  "Donaldson's",
  "Dr Brendan",
  "Duane Reade",
  // E
  "E. T. Slattery",
  "EZCorp",
  "Eddie Bauer",
  "Eileen Fisher",
  "Elder-Beerman",
  "Element Skateboards",
  "Eloquii",
  "Empire Today",
  "Enfants Riches Déprimés",
  "Ex-Boyfriend",
  "Explore Scientific",
  "Express, Inc.",
  "ExtraMile",
  "Exxon",
  // F
  "FAO Schwarz",
  "Fabletics",
  "Famima!!",
  "Famous Footwear",
  "Fanzz",
  "Fashion To Figure",
  "Femme for DKNY",
  "Festival Foods",
  "Filene's",
  "Flax Art Supply Stores",
  "Fleming Companies, Inc",
  "Foley's",
  "Foot Locker",
  "Footstar",
  "Forever 21",
  "Fort Western Stores",
  "Forth & Towne",
  "Fred Segal",
  "Frederick's of Hollywood",
  "Free People",
  "Fretter",
  "Fry's Electronics",
  "Full Compass Systems",
  "Fullbeauty Brands",
  // G
  "G&L Clothing",
  "G-Unit Clothing Company",
  "GNC",
  "GPM Investments",
  "Gadzooks",
  "Gantos",
  "Gap Inc.",
  "Garfinckel's",
  "Garment District",
  "Gart Sports",
  "Gate Petroleum",
  "Geiger's",
  "George Street Co-op",
  "Gerrity's Supermarkets",
  "GetGo",
  "Getty Oil",
  "GiftCards.com",
  "Gilly Hicks",
  "Glik's",
  "Global Industrial",
  "Go-Mart",
  "Godahl Store",
  "Good Guys",
  "Goody's",
  "Gooseberry Patch",
  "Green Earth Market",
  "Guess",
  "Gus Mayer",
  "Gymboree",
  // H
  "H-E-B",
  "H. H. Gregg",
  "Haddock Corporation",
  "Halle Brothers Co.",
  "Hallmark Business Expressions",
  "Halloween Adventure",
  "Halls",
  "Hamer's General Store",
  "Hamilton Shirts",
  "Hamrick's",
  "Han Kjøbenhavn",
  "Hancock Fabrics",
  "Hannaford Brothers Company",
  "Harriet Carter",
  "Harry & David",
  "Harzfeld's",
  "Headsets.com",
  "Hengerer's",
  "Henry's",
  "Herberger's",
  "Hertz Car Sales",
  "Hi-Fi Fo-Fum",
  "Hibbett Sports",
  "Hickey Freeman",
  "High's Dairy Store",
  "Highland Superstores",
  "Hobby Express",
  "Hobby Lobby",
  "HobbyTown USA",
  "Holiday Stationstores",
  "Home Interiors and Gifts",
  "Home Shopping Network",
  "HomeGoods",
  "Horizon Hobby",
  "Hudson's",
  "Hudson's Bay Trading Company",
  // I
  "IFrogz",
  "Incredible Universe",
  "Individualized Apparel Group",
  "Inmac",
  "Island Company",
  // J
  "J Brand",
  "J&R",
  "J. C. Penney",
  "J. Press",
  "J.Crew",
  "J.Lindeberg",
  "Jay Jacobs",
  "Jenni Rivera Fashion",
  "Jerry's Artarama",
  "Jessica McClintock",
  "Jimmy Beans Wool",
  "Jo-Ann Stores",
  "JoS. A. Bank Clothiers",
  "Johnny Cupcakes",
  "Johnston & Murphy",
  "Jr. Food Mart",
  "Jr. Food Stores",
  // K
  "Karmaloop",
  "Kaufmann's",
  "Kenneth Cole Productions",
  "Kinney Shoes",
  "Kinnucan's",
  "Kirkland's",
  "KitSplit",
  "Kitchen Collection",
  "Kitson",
  "Kohl's",
  "Kum & Go",
  "Kuppenheimer",
  "Kwik Shop",
  "Kwik Trip",
  // L
  "L Brands",
  "L.L.Bean",
  "Lamps Plus",
  "Lands' End",
  "Lane Bryant",
  "Lansky Brothers",
  "Lauren Moshi",
  "Lazarus",
  "Le Gourmet Chef",
  "League Collegiate Wear",
  "Learning Express Toys",
  "Legendary Whitetails",
  "Leh's",
  "Leslie's Poolmart",
  "Life is Good Company",
  "Linens 'n Things",
  "Live Breathe Futbol",
  "Loaf 'N Jug",
  "Loeb's",
  "Lolly Wolly Doodle",
  "London Fog",
  "Lord & Taylor",
  "Love's Travel Stops & Country Stores",
  "LuLaRoe",
  "Lucy Activewear",
  // M
  "MFA Oil",
  "MW Tux",
  "MacMall",
  "Macy's",
  "Macy's, Inc.",
  "Madman Muntz",
  "Manic Panic",
  "Manpacks",
  "Marciano Stores",
  "Marmot",
  "Marshalls",
  "Martha Stewart Living Omnimedia",
  "Martin + Osa",
  "Massachusetts Bay Trading Company",
  "Maui and Sons",
  "Maurices",
  "McGinty's Department Store",
  "McKids",
  "Meier & Frank",
  "Merchandize Liquidators",
  "Merchant Customer Exchange",
  "Mervyn's",
  "Metropolis Collectibles",
  "Michael C. Fina",
  "Michael Stars",
  "Michaels",
  "Micro Center",
  "Micro Electronics, Inc.",
  "Microsoft Store",
  "Milly",
  "Minit Mart Foods Inc.",
  "Missouri Star Quilting Company",
  "ModCloth",
  "Monnettes' Market",
  "Moosejaw",
  "Mor Furniture",
  "Morsam Fashions",
  "Mossy Oak",
  "MovieStop",
  "Mt. Vernon Sleep Galleries",
  "New York & Company",
  "Mud Bay pet store",
  "Munchkin Inc.",
  // N
  "NACCO Industries",
  "NBTY",
  "NOCO Energy Corporation",
  "Naartjie",
  "Nabih's Inc.",
  "National Convenience Stores",
  "National Retail Systems",
  "Nau",
  "Navy Exchange",
  "Nebraska Furniture Mart",
  "Neiman Marcus",
  "New Deal Cafe",
  "New Pioneer Food Co-op",
  "Newbury Comics",
  "Newegg",
  "Nigel Beauty Emporium",
  "Nintendo",
  "Nordstrom",
  "Norm Thompson Outfitters",
  "North Shore Shrimp Trucks",
  "Nygård International",
  // O
  "Oakland Cannabis Buyers' Cooperative",
  "Oaklandish",
  "Off Broadway Shoe Warehouse",
  "Office Depot",
  "OfficeMax",
  "Old Navy",
  "On the Run",
  "Palace Lodge",
  "Oneida Limited",
  "Orion Telescopes & Binoculars",
  "Orr's",
  "Orvis",
  "Oshman's Sporting Goods",
  "Ostrow Textile Company",
  "Outdoor Research",
  "OverDrive, Inc.",
  // P
  "P. C. Richard & Son",
  "PCC Community Markets",
  "PCRUSH",
  "PDQ Food Stores",
  "PacSun",
  "Pacific Sales",
  "Pacific Tote Company",
  "Palais Royal",
  "Paper Source",
  "Paperless Post",
  "Paradies Lagardère",
  "Park Slope Food Coop",
  "Party America",
  "Party City",
  "Paul Stuart",
  "Payless ShoeSource",
  "Peaches Boutique",
  "Pearl Art and Craft Supply",
  "Peebles",
  "Pelle Pelle",
  "People's Food Co-op",
  "Pet Supplies Plus",
  "PetSmart",
  "Petco",
  "Petland Discounts",
  "Petro Express",
  "Pilot Corporation",
  "Pilot Flying J",
  "Piperlime",
  "Plaid Pantry",
  "Platt Music",
  "Plow and Hearth",
  "Polk Brothers",
  "Pop Shop",
  "Poppin",
  "Pottery Barn",
  "PriceSmart",
  // Q
  "QVC",
  "Quality Dairy Company",
  "Quick Chek",
  "QuikTrip",
  // R
  "REI",
  "RaceTrac",
  "Rack Room Shoes",
  "Ragstock",
  "Rainbow Computing",
  "Rainbow Shops",
  "Rakuten.com",
  "Raleigh Haberdasher",
  "Ralph Lauren Corporation",
  "Relax The Back",
  "Replacements, Ltd.",
  "Retail Slut",
  "Ridemakerz",
  "Right Start",
  "Rite Rug Flooring",
  "Ritz Camera Centers",
  "Ritz Interactive, Inc.",
  "Road Ranger",
  "Roady's Truck Stops",
  "Robbins Brothers",
  "Robert Hall Clothes",
  "Robot Galaxy",
  "Rocawear",
  "Ron Jon Surf Shop",
  "Room & Board",
  "Roos/Atkins",
  "Ross Stores",
  "Royal Farms",
  "Ruti Zisser",
  "Rutter's",
  // S
  "SAS",
  "SINGER22",
  "SOHOware Incorporated",
  "Saks Fifth Avenue",
  "Salkin & Linoff",
  "Sally Beauty Holdings",
  "Sam's Club",
  "Savers",
  "Sealy Corporation",
  "Sears",
  "Sears Hometown and Outlet Stores",
  "Selena Etc.",
  "Service Merchandise",
  "Sheetz",
  "Shindigz",
  "Shirokiya",
  "ShockHound",
  "Shoe Show",
  "Sierra Trading Post",
  "Silo",
  "SkyMall",
  "Small Dog Electronics",
  "Sophias Style Boutique",
  "Southern Marsh Collection",
  "Southern Tide",
  "Specialty Sports Venture",
  "Speedway LLC",
  "Spencer Gifts",
  "Spirit Halloween",
  "Sport Chalet",
  "Sporting-Sails",
  "Sports Authority",
  "Sports Authority, Inc.",
  "St. Bernard Sports",
  "Stage Stores",
  "Stanley Korshak",
  "Staples Advantage",
  "Staples Inc.",
  "Stern's",
  "Steve & Barry's",
  "Stewart's Shops",
  "Stop-N-Go Foods Inc.",
  "Storables",
  "Strawbridge's",
  "Stripes Convenience Stores",
  "Stroud's Mercantile",
  "Stuckey's",
  "StyleFeeder",
  "Sublime Dreamer",
  "Sullivan Family of Companies",
  "Sun Television and Appliances",
  "Suncoast Motion Picture Company",
  "SuperAmerica",
  "Supreme",
  "Sur La Table",
  "Swanson Health Products",
  "Sweetwater Sound",
  "Swimsuitsforall",
  "Syms Corporation",
  // T
  "T-Shirt Hell",
  "TJ Maxx",
  "TK Maxx",
  "Tailored Brands",
  "Takken's Shoes",
  "Talbots",
  "Target Corporation",
  "Tea Collection",
  "TechStyle Fashion Group",
  "Tedeschi Food Shops",
  "Tekserve",
  "Teleflora",
  "Tempur Sealy International",
  "That's Entertainment",
  "The Apex Companies",
  "The Bon-Ton",
  "The Children's Place",
  "The Container Store",
  "The Fly Stop",
  "The Fresh Market",
  "The Fruit Company",
  "The Grilled Cheese Truck",
  "The Hempest",
  "The Limited",
  "The Maxx",
  "The May Department Stores Company",
  "The Pantry",
  "The Popular",
  "The Wiz",
  "Theor",
  "Thorntons Inc.",
  "Thyme Maternity",
  "TigerDirect",
  "Tilly's",
  "Today's Man",
  "Tom Balding Bits & Spurs",
  "Tom's Convenience Store",
  "Tommy Hilfiger",
  "Tommy Van Scoy",
  "Tori Richard",
  "Torrid",
  "Tory Burch",
  "Tourneau",
  "Town & Country Food Stores",
  "Town Pump",
  "Toy Wizard",
  "Toys \"R\" Us",
  "Trashy Lingerie",
  "TravelCenters of America",
  "True & Co.",
  "Turkey Hill Minit Markets",
  "Tween Brands",
  "Tweete",
  "Twigs Boutique",
  // U
  "US Vision",
  "USA Living",
  "Ulta Beauty",
  "Ultimate Electronics",
  "Uni-Mart",
  "United Cigar Stores",
  "United Dairy Farmers",
  "United Refining Company",
  "Urban Outfitters",
  "UtoteM",
  // V
  "VPS Convenience",
  "Vanity",
  "Variety Wholesalers",
  "Vendo",
  "Venus Fashion",
  "Vermont Country Store",
  "Victoria's Secret",
  "Video Archives",
  "Video Yesteryear",
  "Vineyard Vines",
  "Vitamin World",
  "Von Maur",
  // W
  "W.B. Mason",
  "Walgreens",
  "Warnaco Group",
  "Wawa Inc.",
  "Weavers Way Co-op",
  "Wedge Community Co-op",
  "Wegmans",
  "Weigel's",
  "Wesco",
  "Wesley Berry Flowers",
  "Westport Big & Tall",
  "Wet Seal",
  "Wheatsville Co-op",
  "White Hen Pantry",
  "White House Black Market",
  "Whole Foods Market",
  "WidgetCo, Inc.",
  "Wild Birds Unlimited",
  "Wilkes Bashford",
  "Wirefly",
  "Wireless Emporium",
  "Wisteria",
  "Woodburn Premium Outlets",
  // X
  "Xperience Days",
  // Y
  "Younkers",
  // Z
  "ZCMI",
  "Zany Brainy",
  "Zappos",
  "Zulily"
];
